# Generated by Django 5.1.3 on 2024-12-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
