# Generated by Django 5.1.3 on 2024-12-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_task_end_date_remove_task_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
